#!/bin/bash

# Compile the scripts into a single self-extracting script and package it within a *.tar.bz2

# Exit on most errors
set -e

unset CDPATH

pkgfileslist=("bin" "tools" "files" "installer.sh")
sfxscript="sfx.sh"
readmefile="userdocs/README"
installer="pminstaller.sh"
archive="pminstaller.tar.bz2"

if [[ -z "$1" ]]; then
	pm_hostname="pm4linux.sourceforge.net"
else
	pm_hostname="$1"
fi

cd "$(dirname "$0")"
selfdir="$(pwd)"

if [[ -e build ]]; then
	rm -rf build
fi

echo "Copying required files..."
mkdir build
cp -rv ${pkgfileslist[@]} "$sfxscript" "$readmefile" build/
cd build

# Perform required substitutions
echo "Perform required substitutions in the script(s)..."
sed "s|__HOSTNAME__|$pm_hostname|g" installer.sh > installer.sh.1
mv installer.sh.1 installer.sh

# Minify scripts
echo "Minifying scripts..."
while read filename; do
	if head -n 1 "$filename" | grep -E '^#!/bin/(ba)?sh' &> /dev/null; then
		echo "Minifying $filename..."
		# bash_obfus seems to have some problems with stripping indented comments, so...
		"$selfdir/bash_obfus.plx" -i "$filename" -o /dev/stdout -C -F | grep -Ev '^#[^!]' > "$filename.1"
		mv "$filename.1" "$filename"
	fi
done < <(find . -type f ! -wholename "*/files/*")

# Set permissions
echo "Setting permissions for files in SFX archive..."
while read filename; do
	if head -c 4 "$filename" | grep -E $'(#!|\x7fELF)' &> /dev/null; then
		chmod -v a+x "$filename"
	fi
done < <(find . -type f)

# Prepare SFX
tar --verbose --numeric-owner --group=0 --owner=0 -cJf tmp.tar.xz ${pkgfileslist[@]}
lines=$(($(cat "$sfxscript" | wc -l) + 1))
sed s/__LINENUM__/$lines/ "$sfxscript" > "$installer"
cat tmp.tar.xz >> "$installer"
checksum=$(sed -r s/__CHECKSUM__// "$installer" | sha256sum | grep -Eo [a-f0-9]{64})
sed s/__CHECKSUM__/$checksum/ "$installer" > "$installer.1"
mv "$installer.1" "$installer"

# Package in redistributable format
echo "Packaging installer within tarball..."
chmod -v 755 "$installer"
tar --verbose --numeric-owner --group=0 --owner=0  -cjf "$archive" "$(basename "$readmefile")" "$installer"
find . ! -name "$archive" -delete
