#!/bin/bash

# Make su behave like sudo while accepting arguments.

echo "Please enter the password for root."

while true; do
	su -s /bin/bash -c "$(printf "%q " "$@")"
	errorlevel=$?
	[[ $errorlevel == 0 ]] && break
	read -n 1 -p "Incorrect password. Execution failed. Retry? (Y/N)" ch
	echo # Print \n
	[[ ! "$ch" =~ [Yy] ]] && break
done

exit $errorlevel
